const ADD_ITEM = "ADD_ITEM";
const SELECT_TABLE = "SELECT_TABLE";
const ACTIVE_TABLE = "ACTIVE_TABLE";
const DELETE_ITEM = "DELETE_ITEM";
const INCREASE_MONEY = "INCREASE_MONEY_EARNED";

module.exports = {
  ADD_ITEM,
  SELECT_TABLE,
  ACTIVE_TABLE,
  DELETE_ITEM,
  INCREASE_MONEY
};
